services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule_web_dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "file://./prisma/dev.db"
    volumes:
      - scheduler_db:/app/prisma/dev.db
      - scheduler_node_modules:/app/node_modules

volumes:
  scheduler_db:
<<<<<<< HEAD
  scheduler_node_modules:
=======
  scheduler_node_modules:
>>>>>>> 26f0008f4e380bcb87d9e0f43edf90900082b6a6
